name:                hgbc
version:             0.1.0.0
github:              "CLowcay/hgbc"
license:             BSD3
author:              "Callum Lowcay"
maintainer:          "cwslowcay@gmail.com"
copyright:           "2019 Callum Lowcay"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CLowcay/hgbc#readme>

dependencies:
- OpenGLRaw
- StateVar
- array
- async
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- directory
- file-embed
- filepath
- hashable
- hashtables
- haskeline
- megaparsec
- monad-loops
- mtl
- resourcet
- sdl2
- text
- unordered-containers

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wredundant-constraints
    - -Wpartial-fields
    - -fexpose-all-unfoldings
    - -fspecialise-aggressively
    - -fcross-module-specialise
    - -Wall-missed-specialisations

executables:
  hgbc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hgbc

tests:
  hgbc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hgbc
    - hspec
