name: CI

on:
  push:
    branches: [ master, ci/** ]
  pull_request:
    branches: [ master ]

jobs:
  # Build and run unit tests
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache
      uses: actions/cache@v1.1.2
      env:
        cache-name: stack-dependencies
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock', '**/stack.yaml', '**/package.yaml') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
      
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
      
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install libsdl2-dev
      
    - name: Build and test
      env:
        HSPEC_OPTIONS: --format=failed-examples
      run: |
        stack test --copy-bins --local-bin-path bin

    - uses: actions/upload-artifact@v2
      with:
        name: binaries-linux
        path: bin/

  # Run test ROMS
  rom_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: binaries-linux
        path: bin

    - uses: actions/checkout@v2
      with:
        repository: CLowcay/blargg_roms
        token: ${{ secret.ROMS_TOKEN }}
        path: blargg

    - name: ROM tests
      env:
        BLARGG_DIR: blargg
      run: |
        bin/hgbc-tester
