# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Cache
      uses: actions/cache@v1.1.2
      env:
        cache-name: stack-dependencies
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Get Package
      uses: mstksg/get-package@v1
      with:
        # brew: # optional
        apt-get: libsdl2-dev
      
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
      
    # Runs a set of commands using the runners shell
    - name: Build and test
      run: |
        stack test
